// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBgHtdUuWlz9_bkCT-IRmhWe9j8t2zeQG0",
      authDomain: "solaris-5da18.firebaseapp.com",
      projectId: "solaris-5da18",
      storageBucket: "solaris-5da18.firebasestorage.app",
      messagingSenderId: "229852997499",
      appId: "1:229852997499:web:bdbaa55465dbdb009d7fde",
      measurementId: "G-4T5EKR94NJ");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFSVfpQLKzBTBG-g9qZEVpnoSHN_L8xfM',
    appId: '1:215237081386:android:1e349c97f24c36fa86c653',
    messagingSenderId: '215237081386',
    projectId: 'solaris-app-b2973',
    storageBucket: 'solaris-app-b2973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuqDaaBwi3WLBUHS16sLUF1JgLvosLUi4',
    appId: '1:215237081386:ios:4893d6a39c23274786c653',
    messagingSenderId: '215237081386',
    projectId: 'vidyanexis-app-b2973',
    storageBucket: 'vidyanexis-app-b2973.firebasestorage.app',
    iosBundleId: 'com.example.vidyanexis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKTJiHRyiemSZTH0fUhVIkek8hbI9LBmk',
    appId: '1:215237081386:web:8432d326a14cc34786c653',
    messagingSenderId: '215237081386',
    projectId: 'vidyanexis-app-b2973',
    authDomain: 'vidyanexis-app-b2973.firebaseapp.com',
    storageBucket: 'vidyanexis-app-b2973.firebasestorage.app',
    measurementId: 'G-YCLBX5CCNK',
  );
}
